"use strict";

module.exports = {
  SUCCESS_CODE: 200,
  ALLREADY_EXIST: 201,
  ERROR_CODE: 400,
  AUTH_CODE: 401,

  PROFILEIMAGE: "../backend/app/uploads/profileImages/",

  //LOGIN LOGS
  DEFAULT_PASSWORD: "123456",

  WELCOME_USER_TEMPLATE_CODE: "welcome",
  VERIFICATION_USER_TEMPLATE_CODE: "verification",
  RESET_TEMPLATE_CODE: "reset",
  SIGNIN_SUCCESS: "User successfully Signed In",
  NEW_USER_SAVE_SUCCESS: "New User saved successfully.",
  SOMETHING_WENT_WRONG: "Something went wrong",
  EXT_ERROR: "Please check the extension of file",
  DATA_NOT_FOUND: "Data not found",
  INVALID_LOGIN_DETAILS: "Invalid Login detail",
  UNAUTHORIZE_USER: "User is unauthorised,Kindly verify you account.",
  EMAIL_ALREADY_REGISTERED: "Email already registered.",
  PASSWORD_RESET: "Password Reset Successful",
  SUCCESS_UPLOAD: "Successfully Uploaded Video",
  EXT_ERROR: "Error while Uploading Video",
  UPLOAD_FAILED: "Upload failed",
  VIDEO_LIST_SUCCESS: "Video List fetched successfully",
  VIDEO_LIST_UNSUCCESS: "Oops!Video List was not fetched",
  EMAILTEMPLATE_SAVE_SUCCESS: "Email template saved successfully",
  EMAIL_VERIFIED: "Email verified successfully",
  INTERNAL_ERROR: "Error occured",
  PASSWORD_ERROR: "Password Required",
  TOKEN_ERROR: "Token not found!",
  INVALID_TOKEN: "Invalid Token!",
  CODES_FETCHED: "Codes Fetched Successfully",
  OTP_SEND: "OTP Sent Successfully",
  FAILED_TO_SEND_OTP: "Failed To Send OTP",
  USER_NOT_FOUND: "User Is Not Registered",
  USER_ALREADY_EXIST: "User Already Exist",
  USER_REGISTERED_SUCCESSFULLY: "User Registered Successfully",
  USER_VERIFIED: "User Is Verified",
  REQURIED_FIELDS_NOT: "Required Fields Are Missing",
  USER_UPDATED: "User Updated Successfully",
  SALONS_FOUND: "Solons Nearby Found",
  USER_LOGGED_OUT: "User logged Out Successfully",
  FILE_UNSUPPORTED:"File type is not supported",
  FETCHED_ALL_USERS:"Fetched All Users Successfully"
};
